// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVNdn6pPalynN4TSntFGOs1F2dYH8rX2Y',
    appId: '1:841947643133:web:9b1e2b51220068c4549294',
    messagingSenderId: '841947643133',
    projectId: 'dunia-kopi-app',
    authDomain: 'dunia-kopi-app.firebaseapp.com',
    storageBucket: 'dunia-kopi-app.firebasestorage.app',
    measurementId: 'G-ERLTB0TNJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWpCOu3WuWmq4SYp_UPvsP53bBr80eo0k',
    appId: '1:841947643133:android:2ddf11a7ac3b1eef549294',
    messagingSenderId: '841947643133',
    projectId: 'dunia-kopi-app',
    storageBucket: 'dunia-kopi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvQKuczvpzqeKj6WaYq7R3BVtaYhHAI4Y',
    appId: '1:841947643133:ios:61d9d6ddaabda9e1549294',
    messagingSenderId: '841947643133',
    projectId: 'dunia-kopi-app',
    storageBucket: 'dunia-kopi-app.firebasestorage.app',
    iosBundleId: 'com.example.duniakopiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvQKuczvpzqeKj6WaYq7R3BVtaYhHAI4Y',
    appId: '1:841947643133:ios:61d9d6ddaabda9e1549294',
    messagingSenderId: '841947643133',
    projectId: 'dunia-kopi-app',
    storageBucket: 'dunia-kopi-app.firebasestorage.app',
    iosBundleId: 'com.example.duniakopiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVNdn6pPalynN4TSntFGOs1F2dYH8rX2Y',
    appId: '1:841947643133:web:50d087327cd745d4549294',
    messagingSenderId: '841947643133',
    projectId: 'dunia-kopi-app',
    authDomain: 'dunia-kopi-app.firebaseapp.com',
    storageBucket: 'dunia-kopi-app.firebasestorage.app',
    measurementId: 'G-JLRT209P74',
  );
}
